spring.application.name=orders

# Expondo endpoints específicos (CUIDADO: Nunca use '*' em produção sem blindar com Spring Security)
management.endpoints.web.exposure.include=health,info,metrics
# Exibe detalhes completos no /health sempre
management.endpoint.health.show-details=always

broker.limits.max-order-value=100000
broker.limits.allowed-tickers=MXRF11,ITSA4,KNCR11,PETR4
